### ISSUE TITLE
jemalloc vs mallocng benchmarking?

### ISSUE THREAD

**Issue by brainstorm** [richfelker/mallocng-draft#4]
I've just [noticed that this allocator got switched on by default on MUSL 1.2.1](https://git.musl-libc.org/cgit/musl/commit/?id=ea6d7847ac128f02d1f01ffd01e68341df34ac6e) and will test it soon enough with AWS lambdas (eager to see a `1.0.0` release on [musl-cross-make](https://github.com/richfelker/musl-cross-make)?) :)

Have you run some (rudimentary?) benchmarks vs jemalloc and others to compare?

**Comment by brainstorm** [comment]
jemalloc bench code: https://github.com/jemalloc/jemalloc/commit/753bbf1849caaf4f523567b2da6cb1de6147d811

**Comment by jvoisin** [comment]
Done via https://github.com/daanx/mimalloc-bench/pull/55 :)

**Comment by brainstorm** [comment]
Cool! have you run those and have some plots/numbers to share? :)

**Comment by jvoisin** [comment]
Data should show up at https://github.com/daanx/mimalloc-bench/runs/4273418609?check_suite_focus=true in a couple of minutes if everything goes well.

**Comment by brainstorm** [comment]
According to `elapsed_time` from https://github.com/daanx/mimalloc-bench/runs/4273418609?check_suite_focus=true#step:5:881 ... `malloc-ng` performs quite badly compared to the others? :-S

**Comment by jvoisin** [comment]
Absolutely :/
